apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-collector
  namespace: aws-otel-eks
spec:
  mode: daemonset
  serviceAccount: adot-collector
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      memory_limiter:
        limit_mib: 100
        check_interval: 5s

    exporters:
      awsxray:
        region: ap-southeast-1

    service:
      pipelines:
        traces:
          receivers:
            - otlp
          processors:
            - memory_limiter
          exporters:
            - awsxray
